# Site settings
title: Rust
email: cha452jg@naver.com
description: 시간 날 때마다 틈틈히 관리하는 블로그
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://astrod.github.io" # the base hostname & protocol for your site
twitter_username: -
github_username:  astrod

# Build settings
markdown: kramdown
